(cua-mode 1)
(set-frame-font "Consolas-11")
(setq-default indent-tabs-mode nil)
(setq c-basic-indent 4)
(setq tab-width 4)
(setq make-backup-files nil) 
(global-set-key (kbd "M-w") 'other-window)
(split-window-right)
(setq visible-bell 1)
(defalias 'yes-or-no-p 'y-or-n-p)
;;(setq omnisharp-server-executable-path "F:/Dev/OmniSharpServer/OmniSharp/bin/Debug/Omnisharp.exe")
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)
